[package]
name = "flutter_rust_bridge_template_enhanced"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flutter_rust_bridge_codegen = "=1.78.0"
