#!/usr/bin/env bash

set -e
cargo clean

flutter clean

rm -rf web/pkg

cd native && cargo clean

rm -f \
   ios/Runner/bridge_generated.h \
   lib/bridge_definitions.dart \
   lib/bridge_generated.dart \
   lib/bridge_generated.io.dart \
   lib/bridge_generated.web.dart \
   macos/Runner/bridge_generated.h \
   native/src/bridge_generated.io.rs \
   native/src/bridge_generated.rs \
   native/src/bridge_generated.web.rs \
