#!/usr/bin/env bash

set -e

flutter pub get

cargo build

flutter_rust_bridge_codegen \
   --rust-input native/src/api.rs \
   --dart-output lib/bridge_generated.dart \
   --c-output ios/Runner/bridge_generated.h \
   --extra-c-output-path macos/Runner/ \
   --dart-decl-output lib/bridge_definitions.dart \
   --wasm

cd native && cargo build
