name: builds

on:
  push: 
    branches: [ main ]
  pull_request:

jobs:
  web-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: bash build-scripts/code-gen
      - run: bash build-scripts/build-for-web-deploy
