name: deploy

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: bash build-scripts/build-for-web-deploy
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
         baseHref: /flutter_rust_bridge_template_enhanced/
      - run: tree build
